# Generated by Django 5.0.1 on 2024-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
