# Generated by Django 5.0.1 on 2024-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
