# Generated by Django 5.0.6 on 2024-06-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_cartorder_cartorderitems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorder",
            options={"verbose_name_plural": "4. Orders"},
        ),
        migrations.AlterModelOptions(
            name="cartorderitems",
            options={"verbose_name_plural": "5. Order Items"},
        ),
    ]
