# Generated by Django 5.0.6 on 2024-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_cartorder_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("process", "In Process"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="process",
                max_length=150,
            ),
        ),
    ]
